"""KherveRef citations: library reading, kherveref.bib, serializer,
.ktex bundling, display and the citation picker."""
import json
import os
from pathlib import Path

import pytest

from khervedoc import kdocz, kherveref_link as kr
from khervedoc.model import (Citation, Document, Paragraph, RawLatex, Text,
                             from_json, to_json)
from khervedoc.references import ReferenceResolver
from khervedoc.serializer import serialize_document

LIB_BIB = r"""% generated by KherveRef
@string{jacs = "J. Am. Chem. Soc."}
@article{smith2020surface,
  author  = {Smith, Jane and M{\"{u}}ller, Anna},
  title   = {{XPS} of {TiO2} {surfaces}},
  journal = jacs,
  year    = {2020},
  pages   = {1--2}
}

@book(doe2019book, author = {Doe, John}, title = {A Book (2nd ed.)},
  publisher = {Pub}, year = {2019})
"""


def _doc(*keys, style="citep", library=""):
    d = Document(children=[Paragraph(children=[
        Text(text="See "), *[Citation(keys=[k], style=style) for k in keys]])])
    d.meta.ref_library = library
    return d


@pytest.fixture
def library(tmp_path):
    lib = tmp_path / "MyLib"
    lib.mkdir()
    (lib / "library.bib").write_text(LIB_BIB, encoding="utf-8")
    (lib / "library.json").write_text(json.dumps({"name": "Thesis"}))
    return lib


def test_split_bib():
    entries = kr.split_bib(LIB_BIB)
    assert list(entries) == ["smith2020surface", "doe2019book"]
    assert entries["smith2020surface"].endswith("pages   = {1--2}\n}")
    assert entries["doe2019book"].endswith("year = {2019})")


def test_cited_keys_in_first_citation_order():
    d = _doc("b", "a", "b")
    assert kr.cited_keys(d) == ["b", "a"]


def test_build_bib_order_and_missing():
    text, missing = kr.build_bib(["doe2019book", "nope", "smith2020surface"],
                                 [kr.split_bib(LIB_BIB)])
    assert missing == ["nope"]
    assert text.index("doe2019book") < text.index("smith2020surface")


def test_bibliography_from_library_then_bundle(library):
    d = _doc("smith2020surface", library=str(library))
    text, missing = kr.bibliography_for(d)
    assert "@article{smith2020surface" in text and not missing
    assert "doe2019book" not in text

    # Library gone (another PC): the copy carried by the .ktex is used.
    d.meta.ref_library = str(library.parent / "elsewhere")
    text2, missing2 = kr.bibliography_for(d, bundled=text)
    assert "@article{smith2020surface" in text2 and not missing2

    # The live library wins over a stale bundle.
    stale = text.replace("{2020}", "{1999}")
    d.meta.ref_library = str(library)
    assert "{2020}" in kr.bibliography_for(d, bundled=stale)[0]


def test_known_libraries(library, monkeypatch):
    class FakeSettings:
        def value(self, key, default=None):
            return {"recent_libraries": [str(library), "/nowhere"],
                    "last_library": str(library)}.get(key, default)
    monkeypatch.setattr(kr, "_settings", FakeSettings)
    assert kr.known_libraries() == [library]
    assert kr.library_name(library) == "Thesis"
    (library / "library.json").unlink()
    (library / "My Thesis.kref").write_text(json.dumps({"name": "My Thesis"}))
    assert kr.library_name(library) == "My Thesis"


def test_serializer_adds_bibliography_and_natbib():
    tex = serialize_document(_doc("smith2020surface", library="/lib"))
    assert "\\citep{smith2020surface}" in tex
    assert tex.rstrip().endswith(
        "\\bibliographystyle{plainnat}\n\\bibliography{kherveref}\n\\end{document}")
    assert "\\usepackage{natbib}" in tex


def test_serializer_leaves_unmanaged_documents_alone():
    tex = serialize_document(_doc("x"))
    assert "kherveref" not in tex and "natbib" not in tex


def test_serializer_extends_existing_bibliography():
    d = _doc("smith2020surface", library="/lib")
    d.children.append(RawLatex(text="\\bibliographystyle{unsrt}\n\\bibliography{refs}"))
    tex = serialize_document(d)
    assert "\\bibliography{refs,kherveref}" in tex
    assert tex.count("\\bibliography{") == 1


def test_meta_round_trip():
    d = _doc("a", library="/some/lib")
    d.meta.bib_style = "unsrtnat"
    back = from_json(to_json(d))
    assert (back.meta.ref_library, back.meta.bib_style) == ("/some/lib", "unsrtnat")
    assert from_json(to_json(Document())).meta.bib_style == "plainnat"


def test_ktex_bundles_bib(tmp_path):
    path = tmp_path / "doc.ktex"
    kdocz.save_kdocz(_doc("a", library="/lib"), path, bib_text="@misc{a, title={A}}\n")
    assert kdocz.read_bundled_bib(path) == "@misc{a, title={A}}\n"
    doc, extract = kdocz.load_kdocz(path)
    assert (extract / "kherveref.bib").exists()
    plain = tmp_path / "plain.ktex"
    kdocz.save_kdocz(_doc("a"), plain)
    assert kdocz.read_bundled_bib(plain) == ""


def test_resolver_uses_kherveref_entries():
    d = _doc("smith2020surface", style="citet")
    r = ReferenceResolver(d, None, extra_bib=LIB_BIB)
    assert r.cite_text(["smith2020surface"], "citet") == "Smith and Müller (2020)" \
        or r.cite_text(["smith2020surface"], "citet").startswith("Smith")
    assert "?" not in r.cite_text(["smith2020surface"], "citet")


def test_citation_picker(library, monkeypatch):
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication
    QApplication.instance() or QApplication([])
    monkeypatch.setattr(kr, "known_libraries", lambda: [library])
    from khervedoc.citation_picker import CitationPicker
    dlg = CitationPicker(style="citet")
    assert dlg.library == str(library)
    assert dlg._table.rowCount() == 2
    dlg._search.setText("tio2")
    assert dlg._table.rowCount() == 1
    dlg._table.selectRow(0)
    dlg._manual.setText("other2001, smith2020surface")
    assert dlg.keys() == ["smith2020surface", "other2001"]
    assert dlg.style() == "citet"


def test_picker_offers_bundled_copy(monkeypatch):
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication
    QApplication.instance() or QApplication([])
    monkeypatch.setattr(kr, "known_libraries", lambda: [])
    from khervedoc.citation_picker import CitationPicker
    dlg = CitationPicker(current_library="/gone", bundled_bib=LIB_BIB)
    assert dlg.library == "" and dlg._table.rowCount() == 2


def test_compiles_with_bibtex(library, tmp_path):
    from khervedoc.compiler import compile_tex, tectonic_available
    if not tectonic_available():
        pytest.skip("tectonic not installed")
    d = _doc("smith2020surface", "doe2019book", library=str(library))
    text, missing = kr.bibliography_for(d)
    work = tmp_path / "build"
    work.mkdir()
    (work / kr.BIB_FILE).write_text(text, encoding="utf-8")
    result = compile_tex(serialize_document(d), work)
    assert result.ok, result.error
    import pymupdf
    with pymupdf.open(str(result.pdf_path)) as pdf:
        words = "".join(p.get_text() for p in pdf)
    assert "References" in words and "A Book" in words
    assert "Smith" in words


def test_string_macros_travel_with_entries(library):
    d = _doc("smith2020surface", library=str(library))
    text, _ = kr.bibliography_for(d)
    assert text.index('@string{jacs = "J. Am. Chem. Soc."}') < text.index(
        "@article{smith2020surface")
    assert kr.bibliography_for(_doc("nothing", library=str(library)))[0] == ""


def test_window_cites_saves_bundle_and_reopens(library, tmp_path, monkeypatch):
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication, QDialog
    QApplication.instance() or QApplication([])
    from khervedoc import citation_picker
    from khervedoc.mainwindow import MainWindow
    monkeypatch.setattr(MainWindow, "_kick_compile", lambda self: None)

    class FakePicker:
        def __init__(self, *a, **k):
            self.library = str(library)

        def exec(self):
            return QDialog.Accepted

        def keys(self):
            return ["smith2020surface"]

        def style(self):
            return "citet"

    monkeypatch.setattr(citation_picker, "CitationPicker", FakePicker)
    w = MainWindow()
    try:
        w._new()
        w._insert_citation()
        doc = w._editor.get_document()
        assert doc.meta.ref_library == str(library)
        assert kr.cited_keys(doc) == ["smith2020surface"]
        assert "Smith" in w._editor.text_edit.toPlainText()

        path = tmp_path / "paper.ktex"
        w._current_path = path
        w._write_to(path)
        assert "@article{smith2020surface" in kdocz.read_bundled_bib(path)

        # On a PC without the library the bundled copy keeps it compiling.
        (library / "library.bib").unlink()
        w._open_path(path)
        assert "@article{smith2020surface" in w._bundled_bib
        work = tmp_path / "build"
        w._stage_kherveref_bib(w._editor.get_document(), work)
        assert "@article{smith2020surface" in (work / kr.BIB_FILE).read_text()
    finally:
        w.close()
